name: redemanda
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  another_flushbar: ^1.12.30
  calendar_date_picker2: ^1.1.8
  diacritic: ^0.1.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  go_router: ^14.6.1
  image_picker: ^1.1.2
  open_file: ^3.5.10
  path: ^1.9.0
  path_provider: ^2.1.5
  sembast: ^3.8.0
  sembast_web: ^2.4.0+4
  supabase_flutter: ^2.8.1
  universal_io: ^2.2.2
  window_manager: ^0.4.3
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.3
  service_worker: ^0.4.0
  animate_do: ^3.3.4
  animated_toggle_switch: ^0.8.3
  riverpod_annotation: ^2.6.1
  flutter_hsvcolor_picker: ^1.5.1
  share_plus: ^10.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - .env