name: redemanda
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  another_flushbar: ^1.12.30
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^14.6.1
  image_picker: ^1.1.2
  open_file: ^3.5.10
  supabase_flutter: ^2.8.1
  universal_io: ^2.2.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env