export 'email.dart';
// export 'full_name.dart';
export 'password.dart';
export 'repeat_password.dart';
export 'simple_string_input.dart';
export 'fecha_input.dart';
export 'positive_integer_input.dart';
export 'positive_num_input.dart';
export 'fecha_termino_input.dart';
export 'fecha_accidente_input.dart';
export 'hora_input.dart';
